# Generated by Django 6.0.3 on 2026-03-21 23:58

import django.db.models.deletion
import projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=300)),
                ('maitre_ouvrage', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('responsable_etudes', models.CharField(blank=True, max_length=200)),
                ('consultant_ext', models.CharField(blank=True, max_length=200)),
                ('contrat_moe', models.CharField(blank=True, choices=[('signe', 'Signé et en suivi'), ('projet', 'Projet de contrat'), ('a_verifier', 'Contrat à vérifier')], max_length=20)),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('dormant', 'Dormant'), ('archive', 'Archivé')], default='en_cours', max_length=20)),
                ('phase_actuelle', models.CharField(blank=True, choices=[('EP', 'Études Préliminaires'), ('APS', 'Avant-Projet Sommaire'), ('APD', 'Avant-Projet Détaillé'), ('IPC', 'Instruction du Permis de Construire'), ('PCG', 'Projet de Conception Général'), ('DCE', 'Dossier de Consultation des Entreprises'), ('MDT', 'Mise au Point des Marchés de Travaux'), ('TRAVAUX', 'Travaux')], max_length=20)),
                ('potentiel', models.BooleanField(default=False)),
                ('honoraires', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Intervenant',
                'verbose_name_plural': 'Intervenants',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('declenchement', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=15)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_encaissement', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Acompte',
                'verbose_name_plural': 'Acomptes',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('EP', 'Études Préliminaires'), ('APS', 'Avant-Projet Sommaire'), ('APD', 'Avant-Projet Détaillé'), ('IPC', 'Instruction du Permis de Construire'), ('PCG', 'Projet de Conception Général'), ('DCE', 'Dossier de Consultation des Entreprises'), ('MDT', 'Mise au Point des Marchés de Travaux'), ('TRAVAUX', 'Travaux')], max_length=20)),
                ('etat', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('livre', 'Livré'), ('valide', 'Validé')], default='a_faire', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=projects.utils.deliverable_upload_to)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
            ],
            options={
                'verbose_name': 'Livrable',
                'verbose_name_plural': 'Livrables',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('lien', 'Lien'), ('contact', 'Contact'), ('autre', 'Autre')], default='document', max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('valeur', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to=projects.utils.reference_upload_to)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='projects.project')),
            ],
            options={
                'verbose_name': 'Référence',
                'verbose_name_plural': 'Références',
                'ordering': ['type', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField()),
                ('activite', models.TextField()),
                ('delai', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='projects.project')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.stakeholder')),
            ],
            options={
                'verbose_name': 'Activité hebdomadaire',
                'verbose_name_plural': 'Activités hebdomadaires',
                'ordering': ['semaine_debut', 'stakeholder'],
            },
        ),
    ]
